Update patch set 2
Patch Set 2:

> Patch Set 2: Verified-1
> 
> Build Failed. See OSP CI docs at https://url.corp.redhat.com/ospcidoc 
> 
> https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-cloud-config-tox/301/ : Gate FAILED, you can retrigger tests with comment "recheck"
> 
> No such file or directory ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-cloud-config-tox/301/ )
> 
> command not found ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-cloud-config-tox/301/ )
> 
> Ansible error: "<unicode string>": line 2, column 3, but may ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-cloud-config-tox/301/ )
> 
> InvocationError: could not find executable ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-cloud-config-tox/301/ )
> 
> https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-plugin-cloud-config/321/ : Gate ran successfully

The latest CI failure is due to an ansible-lint failure in an unrelated task file: plugins/cloud-config/tasks/native_fencing.yml. It is not even a part of the role that I am changing.

Patch-set: 2